"""add_rfp_classification_fields

Revision ID: 5174b15420f1
Revises: afa3584e4a7b
Create Date: 2026-09-09 15:54:07.751353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5174b15420f1'
down_revision: Union[str, None] = 'afa3584e4a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfp', sa.Column('primary_category', sa.String(), nullable=True))
    op.add_column('rfp', sa.Column('sub_category', sa.String(), nullable=True))
    op.add_column('rfp', sa.Column('procurement_type', sa.String(), nullable=True))
    op.add_column('rfp', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('rfp', sa.Column('keywords', sa.JSON(), nullable=True))
    op.add_column('rfp', sa.Column('secondary_categories', sa.JSON(), nullable=True))
    op.add_column('rfp', sa.Column('classification_reason', sa.Text(), nullable=True))
    op.add_column('rfp', sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rfp', sa.Column('classification_model', sa.String(), nullable=True))
    op.add_column('rfp', sa.Column('classification_status', sa.String(), server_default=sa.text("'pending'"), nullable=True))
    op.add_column('rfp', sa.Column('classification_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_rfp_classification_status'), 'rfp', ['classification_status'], unique=False)
    op.create_index(op.f('ix_rfp_primary_category'), 'rfp', ['primary_category'], unique=False)
    op.create_index(op.f('ix_rfp_procurement_type'), 'rfp', ['procurement_type'], unique=False)
    op.create_index(op.f('ix_rfp_sub_category'), 'rfp', ['sub_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfp_sub_category'), table_name='rfp')
    op.drop_index(op.f('ix_rfp_procurement_type'), table_name='rfp')
    op.drop_index(op.f('ix_rfp_primary_category'), table_name='rfp')
    op.drop_index(op.f('ix_rfp_classification_status'), table_name='rfp')
    op.drop_column('rfp', 'classification_attempts')
    op.drop_column('rfp', 'classification_status')
    op.drop_column('rfp', 'classification_model')
    op.drop_column('rfp', 'classified_at')
    op.drop_column('rfp', 'classification_reason')
    op.drop_column('rfp', 'secondary_categories')
    op.drop_column('rfp', 'keywords')
    op.drop_column('rfp', 'confidence')
    op.drop_column('rfp', 'procurement_type')
    op.drop_column('rfp', 'sub_category')
    op.drop_column('rfp', 'primary_category')
    # ### end Alembic commands ###
