"""add_designation_and_phone_to_notification_receiver

Revision ID: 5caa68647fd6
Revises: 7ccdd28e9e75
Create Date: 2026-09-16 18:46:47.951736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5caa68647fd6'
down_revision: Union[str, None] = '7ccdd28e9e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_receiver', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('notification_receiver', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_receiver', 'phone')
    op.drop_column('notification_receiver', 'designation')
    # ### end Alembic commands ###
