"""add_notification_receiver_and_website_mapping

Revision ID: 7ccdd28e9e75
Revises: cff4faad5d29
Create Date: 2026-09-16 18:38:29.058232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ccdd28e9e75'
down_revision: Union[str, None] = 'cff4faad5d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_receiver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_receiver_email'), 'notification_receiver', ['email'], unique=False)
    op.create_index(op.f('ix_notification_receiver_id'), 'notification_receiver', ['id'], unique=False)
    op.create_index(op.f('ix_notification_receiver_name'), 'notification_receiver', ['name'], unique=False)
    op.create_table('website_notification_receivers',
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['notification_receiver.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('website_id', 'receiver_id')
    )
    op.add_column('notification', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.alter_column('notification', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'notification', 'notification_receiver', ['receiver_id'], ['id'], ondelete='SET NULL')
    op.add_column('website', sa.Column('notify_all_receivers', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website', 'notify_all_receivers')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.alter_column('notification', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('notification', 'receiver_id')
    op.drop_table('website_notification_receivers')
    op.drop_index(op.f('ix_notification_receiver_name'), table_name='notification_receiver')
    op.drop_index(op.f('ix_notification_receiver_id'), table_name='notification_receiver')
    op.drop_index(op.f('ix_notification_receiver_email'), table_name='notification_receiver')
    op.drop_table('notification_receiver')
    # ### end Alembic commands ###
