"""Add RFP models

Revision ID: aefdacbe7c31
Revises: 5a0f1272f9e7
Create Date: 2026-09-03 15:42:41.010802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aefdacbe7c31'
down_revision: Union[str, None] = '5a0f1272f9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('start_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('crawl_frequency', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_id'), 'website', ['id'], unique=False)
    op.create_index(op.f('ix_website_name'), 'website', ['name'], unique=False)
    op.create_table('crawlrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawlrun_id'), 'crawlrun', ['id'], unique=False)
    op.create_table('rfp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('external_rfp_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('submission_deadline', sa.Date(), nullable=True),
    sa.Column('estimated_budget', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('eligibility', sa.JSON(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('submission_method', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfp_external_rfp_id'), 'rfp', ['external_rfp_id'], unique=False)
    op.create_index(op.f('ix_rfp_id'), 'rfp', ['id'], unique=False)
    op.create_index(op.f('ix_rfp_organization'), 'rfp', ['organization'], unique=False)
    op.create_index(op.f('ix_rfp_reference_number'), 'rfp', ['reference_number'], unique=False)
    op.create_index(op.f('ix_rfp_title'), 'rfp', ['title'], unique=False)
    op.create_table('rfp_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfp_id', sa.Integer(), nullable=False),
    sa.Column('versions', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfp_change_id'), 'rfp_change', ['id'], unique=False)
    op.create_table('rfp_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfp_document_id'), 'rfp_document', ['id'], unique=False)
    op.create_table('rfp_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfp_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfp_version_id'), 'rfp_version', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfp_version_id'), table_name='rfp_version')
    op.drop_table('rfp_version')
    op.drop_index(op.f('ix_rfp_document_id'), table_name='rfp_document')
    op.drop_table('rfp_document')
    op.drop_index(op.f('ix_rfp_change_id'), table_name='rfp_change')
    op.drop_table('rfp_change')
    op.drop_index(op.f('ix_rfp_title'), table_name='rfp')
    op.drop_index(op.f('ix_rfp_reference_number'), table_name='rfp')
    op.drop_index(op.f('ix_rfp_organization'), table_name='rfp')
    op.drop_index(op.f('ix_rfp_id'), table_name='rfp')
    op.drop_index(op.f('ix_rfp_external_rfp_id'), table_name='rfp')
    op.drop_table('rfp')
    op.drop_index(op.f('ix_crawlrun_id'), table_name='crawlrun')
    op.drop_table('crawlrun')
    op.drop_index(op.f('ix_website_name'), table_name='website')
    op.drop_index(op.f('ix_website_id'), table_name='website')
    op.drop_table('website')
    # ### end Alembic commands ###
