"""add_ai_agent_config_table

Revision ID: afa3584e4a7b
Revises: 8c98d4991d94
Create Date: 2026-09-07 17:44:29.942318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa3584e4a7b'
down_revision: Union[str, None] = '8c98d4991d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agent_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('extra_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_agent_config_id'), 'ai_agent_config', ['id'], unique=False)
    op.create_index(op.f('ix_ai_agent_config_is_active'), 'ai_agent_config', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_agent_config_provider'), 'ai_agent_config', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_agent_config_provider'), table_name='ai_agent_config')
    op.drop_index(op.f('ix_ai_agent_config_is_active'), table_name='ai_agent_config')
    op.drop_index(op.f('ix_ai_agent_config_id'), table_name='ai_agent_config')
    op.drop_table('ai_agent_config')
    # ### end Alembic commands ###
