"""add_content_fingerprint_and_llm_cache

Revision ID: cff4faad5d29
Revises: 5174b15420f1
Create Date: 2026-09-16 15:05:45.189554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff4faad5d29'
down_revision: Union[str, None] = '5174b15420f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_cache_cache_key'), 'llm_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_llm_cache_content_hash'), 'llm_cache', ['content_hash'], unique=False)
    op.create_index(op.f('ix_llm_cache_id'), 'llm_cache', ['id'], unique=False)
    op.create_index(op.f('ix_llm_cache_model_name'), 'llm_cache', ['model_name'], unique=False)
    op.create_table('content_fingerprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('normalized_url', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('rfp_id', sa.Integer(), nullable=True),
    sa.Column('extraction_version', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfp.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_fingerprint_content_hash'), 'content_fingerprint', ['content_hash'], unique=False)
    op.create_index(op.f('ix_content_fingerprint_id'), 'content_fingerprint', ['id'], unique=False)
    op.create_index(op.f('ix_content_fingerprint_normalized_url'), 'content_fingerprint', ['normalized_url'], unique=False)
    op.create_index(op.f('ix_content_fingerprint_rfp_id'), 'content_fingerprint', ['rfp_id'], unique=False)
    op.create_index(op.f('ix_content_fingerprint_source_url'), 'content_fingerprint', ['source_url'], unique=False)
    op.create_index(op.f('ix_content_fingerprint_website_id'), 'content_fingerprint', ['website_id'], unique=False)
    op.add_column('rfp', sa.Column('normalized_url', sa.String(), nullable=True))
    op.add_column('rfp', sa.Column('extraction_method', sa.String(), nullable=True))
    op.add_column('rfp', sa.Column('parser_version', sa.Integer(), nullable=True))
    op.add_column('rfp', sa.Column('extraction_version', sa.Integer(), nullable=True))
    op.add_column('rfp', sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfp', 'last_processed_at')
    op.drop_column('rfp', 'extraction_version')
    op.drop_column('rfp', 'parser_version')
    op.drop_column('rfp', 'extraction_method')
    op.drop_column('rfp', 'normalized_url')
    op.drop_index(op.f('ix_content_fingerprint_website_id'), table_name='content_fingerprint')
    op.drop_index(op.f('ix_content_fingerprint_source_url'), table_name='content_fingerprint')
    op.drop_index(op.f('ix_content_fingerprint_rfp_id'), table_name='content_fingerprint')
    op.drop_index(op.f('ix_content_fingerprint_normalized_url'), table_name='content_fingerprint')
    op.drop_index(op.f('ix_content_fingerprint_id'), table_name='content_fingerprint')
    op.drop_index(op.f('ix_content_fingerprint_content_hash'), table_name='content_fingerprint')
    op.drop_table('content_fingerprint')
    op.drop_index(op.f('ix_llm_cache_model_name'), table_name='llm_cache')
    op.drop_index(op.f('ix_llm_cache_id'), table_name='llm_cache')
    op.drop_index(op.f('ix_llm_cache_content_hash'), table_name='llm_cache')
    op.drop_index(op.f('ix_llm_cache_cache_key'), table_name='llm_cache')
    op.drop_table('llm_cache')
    # ### end Alembic commands ###
